language: objective-c
before_install:
  - brew update
  - brew tap homebrew/homebrew-dupes
install:
  - mkdir -pv $(brew --repo)/Library/Taps/travis
  - ln -sv $PWD $(brew --repo)/Library/Taps/travis/travis-testtap
  - brew tap --repair
env:
  - PACKAGE=httpd22
  - PACKAGE=httpd24
script:
  - if [ "$PACKAGE" == "httpd22" ]; then brew install -v $PACKAGE --with-brewed-zlib; fi
  - if [ "$PACKAGE" == "httpd24" ]; then brew install -v $PACKAGE; fi
